-- MySQL Script generated by MySQL Workbench
-- Tue May  5 22:18:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL,
  `e_mail` VARCHAR(45) NULL,
  `second_name` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `e_mail_UNIQUE` (`e_mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ringtone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ringtone` (
  `id` INT NULL,
  `song_name` VARCHAR(45) NULL,
  `singer_name` VARCHAR(45) NULL,
  `duration` INT(20) NULL,
  `ringtonecol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Phone_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Phone_book` (
  `contact_id` INT NOT NULL,
  `phone_number` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `contact_name` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`contact_id`, `user_id`),
  INDEX `fk_Phone_book_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Phone_book_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contact` (
  `id` INT NOT NULL,
  `telegram_id` VARCHAR(45) NULL,
  `notes` VARCHAR(450) NULL,
  `birthday` DATE NULL,
  `address` VARCHAR(45) NULL,
  `e_mail` VARCHAR(45) NULL,
  `ringtone_id` INT NOT NULL,
  `Phone_book_contact_id` INT NOT NULL,
  `Phone_book_user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `ringtone_id`, `Phone_book_contact_id`, `Phone_book_user_id`),
  INDEX `fk_contact_ringtone1_idx` (`ringtone_id` ASC) VISIBLE,
  INDEX `fk_contact_Phone_book1_idx` (`Phone_book_contact_id` ASC, `Phone_book_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_contact_ringtone1`
    FOREIGN KEY (`ringtone_id`)
    REFERENCES `mydb`.`ringtone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_Phone_book1`
    FOREIGN KEY (`Phone_book_contact_id` , `Phone_book_user_id`)
    REFERENCES `mydb`.`Phone_book` (`contact_id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
